import re


INDUSTRY_MAP = {
    "car_dealer": "Automotive",
    "car_rental": "Automotive",
    "car_repair": "Automotive",
    "car_wash": "Automotive",
    "ebike_charging_station": "Automotive",
    "electric_vehicle_charging_station": "Automotive",
    "gas_station": "Automotive",
    "parking": "Automotive",
    "parking_garage": "Automotive",
    "parking_lot": "Automotive",
    "rest_stop": "Automotive",
    "tire_shop": "Automotive",
    "truck_dealer": "Automotive",
    "business_center": "Business & manufacturing",
    "corporate_office": "Business & manufacturing",
    "coworking_space": "Business & manufacturing",
    "farm": "Business & manufacturing",
    "manufacturer": "Business & manufacturing",
    "ranch": "Business & manufacturing",
    "supplier": "Business & manufacturing",
    "television_studio": "Business & manufacturing",
    "art_gallery": "Culture & arts",
    "art_museum": "Culture & arts",
    "art_studio": "Culture & arts",
    "auditorium": "Culture & arts",
    "castle": "Culture & arts",
    "cultural_landmark": "Culture & arts",
    "fountain": "Culture & arts",
    "historical_place": "Culture & arts",
    "history_museum": "Culture & arts",
    "monument": "Culture & arts",
    "museum": "Culture & arts",
    "performing_arts_theater": "Culture & arts",
    "sculpture": "Culture & arts",
    "academic_department": "Education",
    "educational_institution": "Education",
    "library": "Education",
    "preschool": "Education",
    "primary_school": "Education",
    "research_institute": "Education",
    "school": "Education",
    "secondary_school": "Education",
    "university": "Education",
    "adventure_sports_center": "Entertainment & recreation",
    "amphitheatre": "Entertainment & recreation",
    "amusement_center": "Entertainment & recreation",
    "amusement_park": "Entertainment & recreation",
    "aquarium": "Entertainment & recreation",
    "banquet_hall": "Entertainment & recreation",
    "barbecue_area": "Entertainment & recreation",
    "botanical_garden": "Entertainment & recreation",
    "bowling_alley": "Entertainment & recreation",
    "casino": "Entertainment & recreation",
    "childrens_camp": "Entertainment & recreation",
    "city_park": "Entertainment & recreation",
    "comedy_club": "Entertainment & recreation",
    "community_center": "Entertainment & recreation",
    "concert_hall": "Entertainment & recreation",
    "convention_center": "Entertainment & recreation",
    "cultural_center": "Entertainment & recreation",
    "cycling_park": "Entertainment & recreation",
    "dance_hall": "Entertainment & recreation",
    "dog_park": "Entertainment & recreation",
    "event_venue": "Entertainment & recreation",
    "ferris_wheel": "Entertainment & recreation",
    "garden": "Entertainment & recreation",
    "go_karting_venue": "Entertainment & recreation",
    "hiking_area": "Entertainment & recreation",
    "historical_landmark": "Entertainment & recreation",
    "indoor_playground": "Entertainment & recreation",
    "internet_cafe": "Entertainment & recreation",
    "karaoke": "Entertainment & recreation",
    "live_music_venue": "Entertainment & recreation",
    "marina": "Entertainment & recreation",
    "miniature_golf_course": "Entertainment & recreation",
    "movie_rental": "Entertainment & recreation",
    "movie_theater": "Entertainment & recreation",
    "national_park": "Entertainment & recreation",
    "night_club": "Entertainment & recreation",
    "observation_deck": "Entertainment & recreation",
    "off_roading_area": "Entertainment & recreation",
    "opera_house": "Entertainment & recreation",
    "paintball_center": "Entertainment & recreation",
    "park": "Entertainment & recreation",
    "philharmonic_hall": "Entertainment & recreation",
    "picnic_ground": "Entertainment & recreation",
    "planetarium": "Entertainment & recreation",
    "plaza": "Entertainment & recreation",
    "roller_coaster": "Entertainment & recreation",
    "skateboard_park": "Entertainment & recreation",
    "state_park": "Entertainment & recreation",
    "tourist_attraction": "Entertainment & recreation",
    "video_arcade": "Entertainment & recreation",
    "vineyard": "Entertainment & recreation",
    "visitor_center": "Entertainment & recreation",
    "water_park": "Entertainment & recreation",
    "wedding_venue": "Entertainment & recreation",
    "wildlife_park": "Entertainment & recreation",
    "wildlife_refuge": "Entertainment & recreation",
    "zoo": "Entertainment & recreation",
    "public_bath": "Facilities",
    "public_bathroom": "Facilities",
    "stable": "Facilities",
    "accounting": "Finance",
    "atm": "Finance",
    "bank": "Finance",
    "acai_shop": "Food & drink",
    "afghani_restaurant": "Food & drink",
    "african_restaurant": "Food & drink",
    "american_restaurant": "Food & drink",
    "argentinian_restaurant": "Food & drink",
    "asian_fusion_restaurant": "Food & drink",
    "asian_restaurant": "Food & drink",
    "australian_restaurant": "Food & drink",
    "austrian_restaurant": "Food & drink",
    "bagel_shop": "Food & drink",
    "bakery": "Food & drink",
    "bangladeshi_restaurant": "Food & drink",
    "bar": "Food & drink",
    "bar_and_grill": "Food & drink",
    "barbecue_restaurant": "Food & drink",
    "basque_restaurant": "Food & drink",
    "bavarian_restaurant": "Food & drink",
    "beer_garden": "Food & drink",
    "belgian_restaurant": "Food & drink",
    "bistro": "Food & drink",
    "brazilian_restaurant": "Food & drink",
    "breakfast_restaurant": "Food & drink",
    "brewery": "Food & drink",
    "brewpub": "Food & drink",
    "british_restaurant": "Food & drink",
    "brunch_restaurant": "Food & drink",
    "buffet_restaurant": "Food & drink",
    "burmese_restaurant": "Food & drink",
    "burrito_restaurant": "Food & drink",
    "cafe": "Food & drink",
    "cafeteria": "Food & drink",
    "cajun_restaurant": "Food & drink",
    "cake_shop": "Food & drink",
    "californian_restaurant": "Food & drink",
    "cambodian_restaurant": "Food & drink",
    "candy_store": "Food & drink",
    "cantonese_restaurant": "Food & drink",
    "caribbean_restaurant": "Food & drink",
    "cat_cafe": "Food & drink",
    "chicken_restaurant": "Food & drink",
    "chicken_wings_restaurant": "Food & drink",
    "chilean_restaurant": "Food & drink",
    "chinese_noodle_restaurant": "Food & drink",
    "chinese_restaurant": "Food & drink",
    "chocolate_factory": "Food & drink",
    "chocolate_shop": "Food & drink",
    "cocktail_bar": "Food & drink",
    "coffee_roastery": "Food & drink",
    "coffee_shop": "Food & drink",
    "coffee_stand": "Food & drink",
    "colombian_restaurant": "Food & drink",
    "confectionery": "Food & drink",
    "croatian_restaurant": "Food & drink",
    "cuban_restaurant": "Food & drink",
    "czech_restaurant": "Food & drink",
    "danish_restaurant": "Food & drink",
    "deli": "Food & drink",
    "dessert_restaurant": "Food & drink",
    "dessert_shop": "Food & drink",
    "dim_sum_restaurant": "Food & drink",
    "diner": "Food & drink",
    "dog_cafe": "Food & drink",
    "donut_shop": "Food & drink",
    "dumpling_restaurant": "Food & drink",
    "dutch_restaurant": "Food & drink",
    "eastern_european_restaurant": "Food & drink",
    "ethiopian_restaurant": "Food & drink",
    "european_restaurant": "Food & drink",
    "falafel_restaurant": "Food & drink",
    "family_restaurant": "Food & drink",
    "fast_food_restaurant": "Food & drink",
    "filipino_restaurant": "Food & drink",
    "fine_dining_restaurant": "Food & drink",
    "fish_and_chips_restaurant": "Food & drink",
    "fondue_restaurant": "Food & drink",
    "food_court": "Food & drink",
    "french_restaurant": "Food & drink",
    "fusion_restaurant": "Food & drink",
    "gastropub": "Food & drink",
    "german_restaurant": "Food & drink",
    "greek_restaurant": "Food & drink",
    "gyro_restaurant": "Food & drink",
    "halal_restaurant": "Food & drink",
    "hamburger_restaurant": "Food & drink",
    "hawaiian_restaurant": "Food & drink",
    "hookah_bar": "Food & drink",
    "hot_dog_restaurant": "Food & drink",
    "hot_dog_stand": "Food & drink",
    "hot_pot_restaurant": "Food & drink",
    "hungarian_restaurant": "Food & drink",
    "ice_cream_shop": "Food & drink",
    "indian_restaurant": "Food & drink",
    "indonesian_restaurant": "Food & drink",
    "irish_pub": "Food & drink",
    "irish_restaurant": "Food & drink",
    "israeli_restaurant": "Food & drink",
    "italian_restaurant": "Food & drink",
    "japanese_curry_restaurant": "Food & drink",
    "japanese_izakaya_restaurant": "Food & drink",
    "japanese_restaurant": "Food & drink",
    "juice_shop": "Food & drink",
    "kebab_shop": "Food & drink",
    "korean_barbecue_restaurant": "Food & drink",
    "korean_restaurant": "Food & drink",
    "latin_american_restaurant": "Food & drink",
    "lebanese_restaurant": "Food & drink",
    "lounge_bar": "Food & drink",
    "malaysian_restaurant": "Food & drink",
    "meal_delivery": "Food & drink",
    "meal_takeaway": "Food & drink",
    "mediterranean_restaurant": "Food & drink",
    "mexican_restaurant": "Food & drink",
    "middle_eastern_restaurant": "Food & drink",
    "mongolian_barbecue_restaurant": "Food & drink",
    "moroccan_restaurant": "Food & drink",
    "noodle_shop": "Food & drink",
    "north_indian_restaurant": "Food & drink",
    "oyster_bar_restaurant": "Food & drink",
    "pakistani_restaurant": "Food & drink",
    "pastry_shop": "Food & drink",
    "persian_restaurant": "Food & drink",
    "peruvian_restaurant": "Food & drink",
    "pizza_delivery": "Food & drink",
    "pizza_restaurant": "Food & drink",
    "polish_restaurant": "Food & drink",
    "portuguese_restaurant": "Food & drink",
    "pub": "Food & drink",
    "ramen_restaurant": "Food & drink",
    "restaurant": "Food & drink",
    "romanian_restaurant": "Food & drink",
    "russian_restaurant": "Food & drink",
    "salad_shop": "Food & drink",
    "sandwich_shop": "Food & drink",
    "scandinavian_restaurant": "Food & drink",
    "seafood_restaurant": "Food & drink",
    "shawarma_restaurant": "Food & drink",
    "snack_bar": "Food & drink",
    "soul_food_restaurant": "Food & drink",
    "soup_restaurant": "Food & drink",
    "south_american_restaurant": "Food & drink",
    "south_indian_restaurant": "Food & drink",
    "southwestern_us_restaurant": "Food & drink",
    "spanish_restaurant": "Food & drink",
    "sports_bar": "Food & drink",
    "sri_lankan_restaurant": "Food & drink",
    "steak_house": "Food & drink",
    "sushi_restaurant": "Food & drink",
    "swiss_restaurant": "Food & drink",
    "taco_restaurant": "Food & drink",
    "taiwanese_restaurant": "Food & drink",
    "tapas_restaurant": "Food & drink",
    "tea_house": "Food & drink",
    "tex_mex_restaurant": "Food & drink",
    "thai_restaurant": "Food & drink",
    "tibetan_restaurant": "Food & drink",
    "tonkatsu_restaurant": "Food & drink",
    "turkish_restaurant": "Food & drink",
    "ukrainian_restaurant": "Food & drink",
    "vegan_restaurant": "Food & drink",
    "vegetarian_restaurant": "Food & drink",
    "vietnamese_restaurant": "Food & drink",
    "western_restaurant": "Food & drink",
    "wine_bar": "Food & drink",
    "winery": "Food & drink",
    "yakiniku_restaurant": "Food & drink",
    "yakitori_restaurant": "Food & drink",
    "city_hall": "Government",
    "courthouse": "Government",
    "embassy": "Government",
    "fire_station": "Government",
    "government_office": "Government",
    "local_government_office": "Government",
    "neighborhood_police_station": "Government",
    "police": "Government",
    "post_office": "Government",
    "chiropractor": "Health & wellness",
    "dental_clinic": "Health & wellness",
    "dentist": "Health & wellness",
    "doctor": "Health & wellness",
    "drugstore": "Health & wellness",
    "general_hospital": "Health & wellness",
    "hospital": "Health & wellness",
    "massage": "Health & wellness",
    "massage_spa": "Health & wellness",
    "medical_center": "Health & wellness",
    "medical_clinic": "Health & wellness",
    "medical_lab": "Health & wellness",
    "pharmacy": "Health & wellness",
    "physiotherapist": "Health & wellness",
    "sauna": "Health & wellness",
    "skin_care_clinic": "Health & wellness",
    "spa": "Health & wellness",
    "tanning_studio": "Health & wellness",
    "wellness_center": "Health & wellness",
    "yoga_studio": "Health & wellness",
    "apartment_building": "Housing",
    "apartment_complex": "Housing",
    "condominium_complex": "Housing",
    "housing_complex": "Housing",
    "bed_and_breakfast": "Lodging",
    "budget_japanese_inn": "Lodging",
    "campground": "Lodging",
    "camping_cabin": "Lodging",
    "cottage": "Lodging",
    "extended_stay_hotel": "Lodging",
    "farmstay": "Lodging",
    "guest_house": "Lodging",
    "hostel": "Lodging",
    "hotel": "Lodging",
    "inn": "Lodging",
    "japanese_inn": "Lodging",
    "lodging": "Lodging",
    "mobile_home_park": "Lodging",
    "motel": "Lodging",
    "private_guest_room": "Lodging",
    "resort_hotel": "Lodging",
    "rv_park": "Lodging",
    "buddhist_temple": "Places of worship",
    "church": "Places of worship",
    "hindu_temple": "Places of worship",
    "mosque": "Places of worship",
    "shinto_shrine": "Places of worship",
    "synagogue": "Places of worship",
    "aircraft_rental_service": "Services",
    "association_or_organization": "Services",
    "astrologer": "Services",
    "barber_shop": "Services",
    "beautician": "Services",
    "beauty_salon": "Services",
    "body_art_service": "Services",
    "catering_service": "Services",
    "cemetery": "Services",
    "chauffeur_service": "Services",
    "child_care_agency": "Services",
    "consultant": "Services",
    "courier_service": "Services",
    "electrician": "Services",
    "employment_agency": "Services",
    "florist": "Services",
    "food_delivery": "Services",
    "foot_care": "Services",
    "funeral_home": "Services",
    "hair_care": "Services",
    "hair_salon": "Services",
    "insurance_agency": "Services",
    "laundry": "Services",
    "lawyer": "Services",
    "locksmith": "Services",
    "makeup_artist": "Services",
    "marketing_consultant": "Services",
    "moving_company": "Services",
    "nail_salon": "Services",
    "non_profit_organization": "Services",
    "painter": "Services",
    "pet_boarding_service": "Services",
    "pet_care": "Services",
    "plumber": "Services",
    "psychic": "Services",
    "real_estate_agency": "Services",
    "roofing_contractor": "Services",
    "service": "Services",
    "shipping_service": "Services",
    "storage": "Services",
    "summer_camp_organizer": "Services",
    "tailor": "Services",
    "telecommunications_service_provider": "Services",
    "tour_agency": "Services",
    "tourist_information_center": "Services",
    "travel_agency": "Services",
    "veterinary_care": "Services",
    "asian_grocery_store": "Shopping",
    "auto_parts_store": "Shopping",
    "bicycle_store": "Shopping",
    "book_store": "Shopping",
    "building_materials_store": "Shopping",
    "butcher_shop": "Shopping",
    "cell_phone_store": "Shopping",
    "clothing_store": "Shopping",
    "convenience_store": "Shopping",
    "cosmetics_store": "Shopping",
    "department_store": "Shopping",
    "discount_store": "Shopping",
    "discount_supermarket": "Shopping",
    "electronics_store": "Shopping",
    "farmers_market": "Shopping",
    "flea_market": "Shopping",
    "food_store": "Shopping",
    "furniture_store": "Shopping",
    "garden_center": "Shopping",
    "general_store": "Shopping",
    "gift_shop": "Shopping",
    "grocery_store": "Shopping",
    "hardware_store": "Shopping",
    "health_food_store": "Shopping",
    "home_goods_store": "Shopping",
    "home_improvement_store": "Shopping",
    "hypermarket": "Shopping",
    "jewelry_store": "Shopping",
    "liquor_store": "Shopping",
    "market": "Shopping",
    "pet_store": "Shopping",
    "shoe_store": "Shopping",
    "shopping_mall": "Shopping",
    "sporting_goods_store": "Shopping",
    "sportswear_store": "Shopping",
    "store": "Shopping",
    "supermarket": "Shopping",
    "tea_store": "Shopping",
    "thrift_store": "Shopping",
    "toy_store": "Shopping",
    "warehouse_store": "Shopping",
    "wholesaler": "Shopping",
    "womens_clothing_store": "Shopping",
    "arena": "Sports & fitness",
    "athletic_field": "Sports & fitness",
    "fishing_charter": "Sports & fitness",
    "fishing_pier": "Sports & fitness",
    "fishing_pond": "Sports & fitness",
    "fitness_center": "Sports & fitness",
    "golf_course": "Sports & fitness",
    "gym": "Sports & fitness",
    "ice_skating_rink": "Sports & fitness",
    "indoor_golf_course": "Sports & fitness",
    "playground": "Sports & fitness",
    "race_course": "Sports & fitness",
    "ski_resort": "Sports & fitness",
    "sports_activity_location": "Sports & fitness",
    "sports_club": "Sports & fitness",
    "sports_coaching": "Sports & fitness",
    "sports_complex": "Sports & fitness",
    "sports_school": "Sports & fitness",
    "stadium": "Sports & fitness",
    "swimming_pool": "Sports & fitness",
    "tennis_court": "Sports & fitness",
    "airport": "Transportation",
    "airstrip": "Transportation",
    "bike_sharing_station": "Transportation",
    "bridge": "Transportation",
    "bus_station": "Transportation",
    "bus_stop": "Transportation",
    "ferry_service": "Transportation",
    "ferry_terminal": "Transportation",
    "heliport": "Transportation",
    "international_airport": "Transportation",
    "light_rail_station": "Transportation",
    "park_and_ride": "Transportation",
    "subway_station": "Transportation",
    "taxi_service": "Transportation",
    "taxi_stand": "Transportation",
    "toll_station": "Transportation",
    "train_station": "Transportation",
    "train_ticket_office": "Transportation",
    "tram_stop": "Transportation",
    "transit_depot": "Transportation",
    "transit_station": "Transportation",
    "transit_stop": "Transportation",
    "transportation_service": "Transportation",
    "truck_stop": "Transportation",
}


def normalize(value):
    text = str(value).strip().lower()
    text = re.sub(r"[()\.,]", " ", text)
    text = text.replace("&", " and ")
    text = text.replace("-", " ")
    text = text.replace("/", " ")
    return " ".join(text.split())


def to_key(text):
    return text.replace(" ", "_")


KEYWORD_SECTORS = [
    ("dealer", "Automotive"), ("mechanic", "Automotive"),
    ("restaurant", "Food & drink"), ("takeaway", "Food & drink"),
    ("takeout", "Food & drink"), ("cafe", "Food & drink"),
    ("bar", "Food & drink"), ("tiffin", "Food & drink"),
    ("caterer", "Food & drink"), ("catering", "Food & drink"),
    ("kitchen", "Food & drink"), ("distillery", "Food & drink"),
    ("store", "Shopping"), ("shop", "Shopping"),
    ("wholesaler", "Business & manufacturing"), ("wholesale", "Business & manufacturing"),
    ("supplier", "Business & manufacturing"), ("distributor", "Business & manufacturing"),
    ("manufacturer", "Business & manufacturing"), ("processor", "Business & manufacturing"),
    ("printer", "Business & manufacturing"),
    ("school", "Education"), ("education", "Education"),
    ("training", "Education"), ("college", "Education"),
    ("club", "Entertainment & recreation"), ("event", "Entertainment & recreation"),
    ("tour", "Entertainment & recreation"),
    ("consultant", "Services"), ("consulting", "Services"), ("agency", "Services"),
    ("service", "Services"), ("services", "Services"), ("organization", "Services"),
    ("charity", "Services"), ("broker", "Services"), ("cleaner", "Services"),
    ("cleaners", "Services"), ("cleaning", "Services"), ("storage", "Services"),
    ("recruiter", "Services"), ("contractor", "Services"), ("remodeler", "Services"),
    ("designer", "Services"), ("fitter", "Services"),
    ("care", "Health & wellness"), ("nursing", "Health & wellness"),
    ("optometrist", "Health & wellness"),
    ("housing", "Housing"),
    ("accommodation", "Lodging"), ("lodging", "Lodging"),
    ("architect", "Services"), ("engineer", "Services"), ("builder", "Services"),
    ("hairdresser", "Services"), ("jeweler", "Shopping"), ("jeweller", "Shopping"),
    ("photographer", "Services"), ("photography", "Services"),
]
KEYWORD_SECTORS.sort(key=lambda pair: len(pair[0]), reverse=True)


def derive_industry(category_value):
    norm = normalize(category_value)
    key = to_key(norm)
    if key in INDUSTRY_MAP:
        return INDUSTRY_MAP[key]

    words = set(norm.split())
    for phrase, sector in KEYWORD_SECTORS:
        if " " in phrase:
            if phrase in norm:
                return sector
        else:
            if phrase in words:
                return sector

    for map_key, sector in INDUSTRY_MAP.items():
        map_phrase = map_key.replace("_", " ")
        if map_phrase in norm and len(map_phrase) > 4:
            return sector

    return "Other"
